add_newline = false

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 0

[git_branch]
truncation_length = 18
style = "bold green"

[nodejs]
disabled = true

[package]
disabled = true

[character]
error_symbol = "✗"
use_symbol_for_status = true
style_failure = "#A84055"